---
title: "Statistic wirh R by FUN  - Week 1"
output: 
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(prettyR)
```

## Example Chi-2 test 

### With 100 people in each group

```{r}
p.Mal <- c(.7, .6)
p.Gue <- c(.3, .4)
p.matrix <- matrix(data = c(p.Gue*100, p.Mal*100), ncol = 2)
p.matrix
chisq.test(x= p.matrix,correct = FALSE)


```
### With 200 individuals in each group
```{r}
p.matrix <- matrix(data = c(p.Gue*200, p.Mal*200), ncol = 2)
p.matrix
chisq.test(x= p.matrix,correct = FALSE)
```


### With 1000 individuals in each group
```{r}
p.matrix <- matrix(data = c(p.Gue*1000, p.Mal*1000), ncol = 2)
p.matrix
chisq.test(x= p.matrix,correct = FALSE)
```



## Load data from csv file

```{r load_data, cache=TRUE}

smp <- read.csv2("./smp1.csv")

smp2 <- read.csv2("./smp2.csv")

```

## See statistics for smp
```{r summary_data}

summary(smp)

describe(smp)

describe(smp, num.desc = c("mean", "median", "sd", "min", "max", "valid.n"))

```


## See statistics for smp2
```{r summary_data2}

summary(smp2)

describe(smp2)

describe(smp2, num.desc = c("mean", "median", "sd", "min", "max", "valid.n"))

```


## draw charts



```{r draw_charts, echo=TRUE}

ggplot(smp, aes(x= rs, y= age, group = rs)) + geom_boxplot(outlier.colour = "red")

ggplot(smp, aes(prof, fill = prof)) + geom_bar()

ggplot(as.data.frame(round(prop.table(table(smp$prof))*100,2)), aes(x = Var1, y = Freq, fill = Var1)) + geom_bar(width = .5, stat = "identity")

ggplot(as.data.frame(table(smp$prof)), aes(x = "", y = Freq, fill = Var1)) + geom_bar(width = .5, stat = "identity", position = position_stack()) + coord_polar('y')

ggplot(smp, aes(x= jitter(age), y = jitter(n.enfant), colour = age)) + geom_point()


```


## Mean comparaison

### define new variables
```{r}
smp$ed.b <- smp$ed > 2
smp$ed.b <- ifelse(smp$ed > 2, 1, 0)
table(smp$ed.b, useNA = "always")


```

### compute variance/standard for each group
```{r}
smp %>%
  group_by(ed.b) %>%
  summarize(age_sd = sd(age,na.rm = TRUE))
```

### plot the age histogram
```{r}
smp %>%
  ggplot(aes(x=age, color = "red")) +
  geom_histogram(binwidth = 5)
```



